spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://database-cbiostapi.coy7x3znz5va.sa-east-1.rds.amazonaws.com:3306/cbiost
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true